const bookmarks = [
  { id: 1,
    title: 'Thinkful',
    description: 'Think outside the classroom',
    url: 'https://www.thinkful.com',
    rating: 5 },
  { id: 2,
    title: 'Google',
    description: '',
    url: '',
    rating:  4},
  { id: 3,
    title: 'MDN',
    description: '',
    url: '',
    rating:  5},
  { id: 4,
    title: 'T-Nation',
    description: '',
    url: '',
    rating:  5},
  { id: 5,
    title: 'random',
    description: '',
    url: '',
    rating: 2 },
]

module.exports = {bookmarks}
